services:
  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      PGDATA: "/data/postgres"
      POSTGRES_DB: Acervo
    networks:
      - acervo
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped

  db:
    image: postgres
    container_name: metabase_db
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase
      POSTGRES_DB: metabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - acervo
    restart: unless-stopped

  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=metabase
      - MB_DB_HOST=db
    depends_on:
      - db
    networks:
      - acervo
    restart: unless-stopped

volumes:
  postgres:
  postgres-data:

networks:
  acervo:
    driver: bridge
