services:
  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      PGDATA: "/data/postgres"
      POSTGRES_DB: Acervo
    networks:
      - acervo
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - acervo
    restart: unless-stopped

volumes:
  pgadmin:
  postgres:

networks:
  acervo:
    driver: bridge
